---
title: "Priority_needs_SOM"
author: "Lisa Thalheimer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages 

```{r}
library(tidyverse)
library(janitor)
library(readr)
library(skimr)
library(dplyr)
library(lubridate)
library(here)
library(readxl)
library(ggplot2)
library(circlize)
library(janitor)
library(lubridate)
library(RColorBrewer)
library(extrafont)
library(reshape)
```


## Import file 
```{r pressure, echo=FALSE}
#Import survey file and naming the raw data frame UNHCR_raw
UNHCR_raw <- read_excel("UNHCR-PRMN-Displacement-Dataset.xlsx") %>%
  clean_names()
  
```

```{r pressure, echo=FALSE}
#Cleaning up the raw data frame and sub-setting UNHCR data frame

UNHCR <- UNHCR_raw %>% 
  mutate(month_end = dmy(month_end)) %>% 
  mutate(year = year(month_end)) %>%
  mutate(month = month(month_end, label = TRUE)) %>% 
  # relocate(month) %>% 
  dplyr::rename(
    destination = current_arrival_region, 
         origin = previous_departure_region,
         people = number_of_individuals,
    priority_need = current_arrival_priority_need) %>% 
  filter(priority_need == "Food") %>%   #only showing Food as priority need 
  select(-contains("district")) %>% # drop district level data 
  select(-"month_end", -"year_week") %>% 
  filter(year %in% c("2016", "2017", "2018","2019")) 
  
```


## Plotting the circos plot

```{r pressure, echo=FALSE}
options(scipen = 30, digits = 1) # turns off scientific notation


# set plot parameters and colors, and format numbers
kelly.colours <- c("gray95", "gray13", "gold2",
                   "plum4", "darkorange1", "lightskyblue2",
                   "firebrick", "burlywood3", "gray51",
                   "springgreen4", "lightpink2", "deepskyblue4",
                   "lightsalmon2", "mediumpurple4", "orange",
                   "maroon", "yellow3", "brown4") # "yellow4", "sienna4", "chocolate", "gray19")


for(i in c("all","Drought related","Conflict/Insecurity")){
  # i = "all"
  
  
  UNHCR %>% 
    {if(i != "all"){
      filter(.,reason == i) #removed reason 
    } else {
      .   
    }} %>% 
    group_by(destination, origin) %>% 
    summarise(people = sum(people),.groups = "drop")-> df_ready
  
  png(
    width = 6,
    height = 6,
    file = here(paste0("figures/circosplots",switch(i,
                                                           all = "Total",
                                                           `Drought related` = "Drought",
                                                           `Conflict/Insecurity` = "Conflict"), ".png")),
    units = "in",
    res = 600,
    # family = "Myriad Pro"
  )
  
  circos.clear()
  par(mar = c(0,0,1,0)) # these are the margins and size
  circos.par(
    #start.degree = 180,
    start.degree = 90,
    gap.degree = 4,
    track.margin = c(-0.1, 0.1),
    points.overflow.warning = FALSE
  )
  
  chordDiagram(df_ready, directional = 1,
    direction.type = c("arrows", "diffHeight"),
    diffHeight = -0.01,
    link.arr.type = "big.arrow",
    grid.col = kelly.colours,
    annotationTrack = "grid",
    link.sort = TRUE,
    link.largest.ontop = TRUE,
    preAllocateTracks = 1 # default was 1
  )
  
  circos.trackPlotRegion(track.index = 1, 
                         panel.fun = function(x, y) {
                           xlim = get.cell.meta.data("xlim")
                           # ylim = get.cell.meta.data("ylim")
                           sector.name = get.cell.meta.data("sector.index")
                           circos.text(x = mean(xlim), # to make sure it's centred 
                                       y = 0.8, # distance to the out boundard
                                       labels = gsub(" ","\n",sector.name), # spaces replaced with linebreak
                                       #facing = "downward", 
                                       facing = "clockwise", 
                                       niceFacing = TRUE, 
                                       # family = "Myriad Pro",
                                       col = "gray30", 
                                       cex = 0.7)
                         }, bg.border = NA)
  
  
  # Units on the axis
  circos.trackPlotRegion(track.index = 2, 
                         panel.fun = function(x, y) {
                           sector.name = get.cell.meta.data("sector.index")
                           circos.axis(
                             h = "top",
                             labels.cex = 0.5,
                             sector.index = sector.name,
                             labels.niceFacing = TRUE,
                             labels.pos.adjust = FALSE
                           )}, bg.border = NA)
  
  
  # add title, labels and axis
  title(
    main = switch(i,
                  all = "Food as Priority Need of Total IDPs",
                  `Drought related` = "Drought IDPs",
                  `Conflict/Insecurity` = "Conflict IDPs"),
    cex.main = 1,
    # family = "Myriad Pro", 
    line = -1 # to make sure the title is a bit closer to the plot (reduces whitespace)
  )
  
  dev.off()
  
}


library(png)
library(grid)
library(gridExtra)
l <- readPNG(here("figures/circosplotsTotal.png"))
m <- readPNG(here("figures/circosplotsDrought.png"))
r <- readPNG(here("figures/circosplotsConflict.png"))


combined <- grid.arrange(rasterGrob(l),rasterGrob(m), rasterGrob(r),nrow=1)
ggsave(combined, filename = here("figures/circosplots_combined.png"),width = 6, height = 4, dpi = 1000)

```

